<a href="https://colab.research.google.com/github/RoseVZ/TensorflowCert/blob/main/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
 import tensorflow as tf
 print(tf.__version__)

2.8.2


## Creation of Scalars

In [20]:
scalar  = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [15]:
vector= tf.constant([2,3])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [18]:
#no of dimension
vector.ndim

1

In [28]:
#tensor
tensor = tf.constant([[[3,4],
                      [6,5],
                      [3,5]
                   
],[[3,4],[4,5],[4,5]]])
tensor


<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[3, 4],
        [6, 5],
        [3, 5]],

       [[3, 4],
        [4, 5],
        [4, 5]]], dtype=int32)>

In [29]:
tensor.ndim

3

In [30]:
variable_tensor = tf.Variable([3,4])

In [36]:
variable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 4], dtype=int32)>

In [37]:
print(variable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 4], dtype=int32)>


## Random Tensors

In [41]:
random_1= tf.random.Generator.from_seed(30)
random_1 = random_1.normal(shape=(3,2))

In [42]:
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.8357487 ,  0.20849545],
       [ 1.4040174 , -2.735283  ],
       [ 1.2232229 , -1.8653691 ]], dtype=float32)>

## Shuffle Tensor 

In [43]:
unshuffled = tf.constant([[3,4],[7,8]])
shuffled = tf.random.shuffle(unshuffled,seed = 3) #seed here is an operational seed
shuffled

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 8],
       [3, 4]], dtype=int32)>

##Set Seed

In [44]:
#universal seed
tf.random.set_seed(7)

## Creation of tensors in various ways

In [45]:
tf.ones((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [46]:
tf.zeros(shape= (4,2))

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

## Numpy to Tf

In [47]:
import numpy as np

In [50]:
np_array = np.arange(1,5, dtype= np.int32)
np_array

array([1, 2, 3, 4], dtype=int32)

In [54]:
#conversion
tf.constant(np_array, shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

## Tensor Atributes