<a href="https://colab.research.google.com/github/RoseVZ/TensorflowCert/blob/main/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
 import tensorflow as tf
 print(tf.__version__)

2.8.2


## Creation of Scalars

In [2]:
scalar  = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
vector= tf.constant([2,3])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [4]:
#no of dimension
vector.ndim

1

In [5]:
#tensor
tensor = tf.constant([[[3,4],
                      [6,5],
                      [3,5]
                   
],[[3,4],[4,5],[4,5]]])
tensor


<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[3, 4],
        [6, 5],
        [3, 5]],

       [[3, 4],
        [4, 5],
        [4, 5]]], dtype=int32)>

In [6]:
tensor.ndim

3

In [7]:
variable_tensor = tf.Variable([3,4])

In [8]:
variable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 4], dtype=int32)>

In [9]:
print(variable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 4], dtype=int32)>


## Random Tensors

In [10]:
random_1= tf.random.Generator.from_seed(30)
random_1 = random_1.normal(shape=(3,2))

In [11]:
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.8357487 ,  0.20849545],
       [ 1.4040174 , -2.735283  ],
       [ 1.2232229 , -1.8653691 ]], dtype=float32)>

## Shuffle Tensor 

In [12]:
unshuffled = tf.constant([[3,4],[7,8]])
shuffled = tf.random.shuffle(unshuffled,seed = 3) #seed here is an operational seed
shuffled

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 8],
       [3, 4]], dtype=int32)>

##Set Seed

In [13]:
#universal seed
tf.random.set_seed(7)

## Creation of tensors in various ways

In [14]:
tf.ones((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [15]:
tf.zeros(shape= (4,2))

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

## Numpy to Tf

In [16]:
import numpy as np

In [17]:
np_array = np.arange(1,5, dtype= np.int32)
np_array

array([1, 2, 3, 4], dtype=int32)

In [18]:
#conversion
tf.constant(np_array, shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

## Tensor Atributes

In [21]:
rank_4_tensor = tf.ones(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [24]:
rank_4_tensor.ndim, tf.size(rank_4_tensor), tf.shape(rank_4_tensor)

(4,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>)

In [26]:
print("Datatype",rank_4_tensor.dtype )
print("Dimensions",rank_4_tensor.ndim)
print("Shape of tensor", tf.shape(rank_4_tensor))
print("Element of 0th place", rank_4_tensor[0])
print("Size of tensor", tf.size(rank_4_tensor))

Datatype <dtype: 'float32'>
Dimensions 4
Shape of tensor tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)
Element of 0th place tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 4, 5), dtype=float32)
Size of tensor tf.Tensor(120, shape=(), dtype=int32)


## Indexing a tensor

In [27]:
rank_4_tensor[:1,:1,:1,:1
              ]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[1.]]]], dtype=float32)>

In [29]:
#rank 2 tensor
rank_2_tensor = tf.constant([[10,7],[12,3]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [12,  3]], dtype=int32)>

In [30]:
#last index of every row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 3], dtype=int32)>

In [31]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[12],
        [ 3]]], dtype=int32)>

In [32]:
rank_3_tensor.ndim

3

In [34]:
rank_3 = tf.expand_dims(rank_2_tensor,axis=-1)
rank_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[12],
        [ 3]]], dtype=int32)>

## Operations on Tensor


In [3]:
tensor = tf.constant([[10,12],[10,20]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 22],
       [20, 30]], dtype=int32)>

In [4]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 120],
       [100, 200]], dtype=int32)>

In [5]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 12],
       [10, 20]], dtype=int32)>

## Matrix Multiplication


In [6]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[220, 360],
       [300, 520]], dtype=int32)>

In [7]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[220, 360],
       [300, 520]], dtype=int32)>

In [8]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 144],
       [100, 400]], dtype=int32)>

In [9]:
tesor4 = tf.constant([2,2])
tesor4.shape

TensorShape([2])

In [11]:
tf.reshape(tesor4,shape=(2,1))

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [2]], dtype=int32)>

In [12]:
tf.matmul(tensor,tf.reshape(tesor4,shape=(2,1)))

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[44],
       [60]], dtype=int32)>

In [14]:

#tensordot
tf.tensordot(tensor,tf.reshape(tesor4,shape=(2,1)), axes=1)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[44],
       [60]], dtype=int32)>

## Changing the Dtype

In [15]:
b=tf.constant([1.3])
b.dtype

tf.float32

In [17]:
c=tf.constant([1,2])
c.dtype

tf.int32

In [18]:
b=tf.cast(b,dtype = tf.float16)
b

<tf.Tensor: shape=(1,), dtype=float16, numpy=array([1.3], dtype=float16)>

In [20]:
b=tf.cast(b,dtype = tf.int32)
b

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>