<a href="https://colab.research.google.com/github/RoseVZ/TensorflowCert/blob/main/Tensor_basics2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
tf.__version__

'2.8.2'

In [4]:
import numpy as np

## Tensor (Aggregrating)

### Absolute Value

In [5]:
D= tf.constant([-1,-2])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -2], dtype=int32)>

In [6]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

### Minimum, Max

In [7]:
e= tf.constant(np.random.randint(0,100,size= 50))
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([25, 45, 77, 19, 24, 54, 31,  0, 82, 34, 58, 75, 49, 13, 26, 70, 97,
       93,  8, 84, 44,  1, 64, 42, 16,  6, 68, 30, 45, 65, 44, 73, 70, 86,
       81, 67, 93, 16, 36, 31, 26, 93, 54, 49, 64, 93, 56, 79,  5, 70])>

In [8]:
e.shape

TensorShape([50])

In [9]:
tf.reduce_min(e 
              )

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [10]:
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

###Sum

In [11]:
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [12]:
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2531>

In [13]:
import tensorflow_probability as tfp

In [24]:
tf.math.reduce_variance(tf.cast(e,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=775.83563>

In [22]:
tf.math.reduce_std(tf.cast(e,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.853827>

## Max/Min **Argument**

In [25]:
#return position
tf.argmax(e)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [26]:
e[tf.argmax(e)] 
#returns max value

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [28]:
tf.argmin(e)

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [29]:
e[tf.argmin(e)]

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [31]:
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [33]:
tf.argmax(e)==tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=bool, numpy=False>

## Squeezing a TENSOR

In [36]:
g= tf.random.uniform(shape=[1,1,1,5])
g 
g.shape

TensorShape([1, 1, 1, 5])

In [37]:
g

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=
array([[[[0.9744512 , 0.37235844, 0.55775476, 0.65359855, 0.70076346]]]],
      dtype=float32)>

In [40]:
#squuezing
g_squeezed = tf.squeeze(g)
g_squeezed.shape, g_squeezed

(TensorShape([5]), <tf.Tensor: shape=(5,), dtype=float32, numpy=
 array([0.9744512 , 0.37235844, 0.55775476, 0.65359855, 0.70076346],
       dtype=float32)>)

## ONe hot End=coding

In [43]:
list1 = [1,2,3]
tf.one_hot(list1 ,depth=4)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

## Other operations
1. Square root : tf.sqrt(pass float value)
2. Range : returns values with in the range mentioned
3. Log: tf.log(pass value as float32)
4. Square: tf.square()

## Numpy and Tensor


### Conversion of numpy array to tensor

In [44]:
x= np.array([2.,3.,4.])
y= tf.constant(x)
y

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 3., 4.])>

### Conversion of  tensor to numpy array 

In [47]:
 l= np.array(y)
 l

array([2., 3., 4.])

In [48]:
y

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 3., 4.])>

In [50]:
y.numpy()


array([2., 3., 4.])

In [51]:
type(y.numpy())

numpy.ndarray

## 👁 Tensors created from Numpy are of type ***Float64*** vs the other is ***Float 32***

## Gpu Usuage

In [1]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
!nvidia-smi

Fri Aug 26 09:34:28 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------