<a href="https://colab.research.google.com/github/RoseVZ/TensorflowCert/blob/main/Tensor_basics2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
tf.__version__

'2.8.2'

In [5]:
import numpy as np

## Tensor (Aggregrating)

### Absolute Value

In [3]:
D= tf.constant([-1,-2])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -2], dtype=int32)>

In [4]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

### Minimum, Max

In [7]:
e= tf.constant(np.random.randint(0,100,size= 50))
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([15, 23, 95, 35, 84, 90, 93, 28, 22, 56, 43, 19, 51, 63, 86, 82,  5,
       40, 16, 12, 17, 26, 22, 64, 95,  2, 69, 86, 13,  0, 15, 87, 28, 22,
       45, 75, 18, 26, 44, 88, 68, 45, 64, 14,  4, 43, 20,  1, 12, 40])>

In [8]:
e.shape

TensorShape([50])

In [9]:
tf.reduce_min(e 
              )

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [10]:
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=95>

###Sum

In [11]:
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [13]:
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2111>